//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.34003
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Extra {

	public class Tuple<T1, T2> {
		public T1 First { get; private set; }

		public T2 Second { get; private set; }

		internal Tuple (T1 first, T2 second) {
			First = first;
			Second = second;
		}
	}
	
	public static class Tuple {
		public static Tuple<T1, T2> New<T1, T2> (T1 first, T2 second) {
			var tuple = new Tuple<T1, T2> (first, second);
			return tuple;
		}
	}
}

